# Generated by Django 4.0.4 on 2022-04-12 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weatherData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 19, 8, 22, 592947, tzinfo=utc)),
        ),
    ]
